##########################################
## Garage Door Automations              ##
##########################################
- alias: 'Open Gate Upon Arrival'
  trigger:
  - platform: state
    entity_id: group.all_devices
    from: not_home
    to: home 
  condition:
  - condition: state
    entity_id: cover.gate
    state: 'closed'
  action:
  - service: cover.open_cover
    entity_id: cover.gate