## Updated to v6 for GitPull Testing ##
homeassistant:

  name: !secret ha_name
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: !secret ha_elevation
  unit_system: imperial
  time_zone: America/Chicago 
  customize: !include_dir_merge_named customizations
  packages: !include_dir_named packages
  

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret http_address
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor:
  # Weather prediction
  - platform: yr

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# Covers (GarageDoor and Gate)
cover:
  - platform: myq
    username: !secret cover_username
    password: !secret cover_password
    type: liftmaster

vera:
  vera_controller_url: http://192.168.1.48:3480/

nest:
  client_id: !secret nest_clientid
  client_secret: !secret nest_clientsecret

# ios Config
ios:

group: !include groups.yaml
#automation: !include automations.yaml
script: !include scripts.yaml